GET https://8080-joseaugusto83-j2a1-ddpu5yw6zc7.ws-us115.gitpod.io/frutas

###

GET https://8080-joseaugusto83-j2a1-ddpu5yw6zc7.ws-us115.gitpod.io/frutas/0

###

POST https://8080-joseaugusto83-j2a1-ddpu5yw6zc7.ws-us115.gitpod.io/frutas
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "Nova Fruta": "Nova fruta"
}